# Generated by Django 3.2.9 on 2021-11-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flipkartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cartapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.cartapp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkartapp.prod')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
